version: "3"
services: 
  my-api:
    build: .
    volumes:
      - /app/node_modules
      - ./:/app
    environment:
      - NODE_ENV=development
    command: npm run dev
    env_file:
      - .env
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=Azaa
      - MONGO_INITDB_ROOT_PASSWORD=Password

volumes:
  mongo_data: